apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fluenthose.fullname" . }}
  labels:
    {{- include "fluenthose.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fluenthose.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fluenthose.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fluenthose.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: fluenthose
          args:
            {{- range $i, $arg := .Values.fluenthose.args }}
            - "{{ $arg }}"
            {{- end }}
          env:
            - name: FLUENTHOSE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: FLUENTHOSE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "fluenthose.fullname" . }}
                  key: accessKey
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.fluenthose.image.repository }}:{{ .Values.fluenthose.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.fluenthose.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
          resources:
            {{- toYaml .Values.fluenthose.resources | nindent 12 }}
        - name: fluentbit
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.fluentbit.image.repository }}:{{ .Values.fluentbit.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.fluentbit.image.pullPolicy }}
          ports:
            - name: api
              containerPort: 2020
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: api
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: api
          resources:
            {{- toYaml .Values.fluentbit.resources | nindent 12 }}
          volumeMounts:
            - name: fluentbit-config
              mountPath: /fluent-bit/etc
              readOnly: true
      volumes:
        - name: fluentbit-config
          configMap:
            name: {{ include "fluenthose.fullname" . }}
            items:
              - key: fluent-bit.conf
                path: fluent-bit.conf
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
