apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fluenthose.fullname" . }}
  labels:
    {{- include "fluenthose.labels" . | nindent 4 }}
type: Opaque
data:
  accessKey: {{ .Values.config.accessKey | b64enc}}