apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluenthose.fullname" . }}
  labels:
    {{- include "fluenthose.labels" . | nindent 4 }}
  annotations:
    {{- .Values.service.annotations | toYaml | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fluenthose.selectorLabels" . | nindent 4 }}
