# Default values for fluenthose.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

config:
  accessKey: CHANGEME
  listen:
    address: ":8080"
  logLevel: info
  loki:
    address: loki.tld
    tls: on
    port: 443
    auth:
      user: loki
      password: loki
  # fluentbit_conf: |
  #   [SERVICE]
  #     HTTP_Server  On
  #     HTTP_Listen  0.0.0.0
  #     HTTP_PORT    2020
  #     Health_Check On 
  #     HC_Errors_Count 5 
  #     HC_Retry_Failure_Count 5 
  #     HC_Period 5
  #     Flush 1
  #     Parsers_File /fluent-bit/etc/parsers.conf
  #   [INPUT]
  #     Name              forward
  #     Listen            127.0.0.1
  #     Port              24224
  #     Buffer_Chunk_Size 512K
  #     Buffer_Max_Size   512K

service:
  type: LoadBalancer
  port: 443
  externalTrafficPolicy: Local
  annotations: {}
    # external-dns.alpha.kubernetes.io/hostname: fluenthose.somedomain.com.
    # external-dns.alpha.kubernetes.io/ttl: "60"
    # service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    # service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-central-1:XXX:certificate/XXX-XXX-XXX-XXX
    # service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    # service.beta.kubernetes.io/aws-load-balancer-internal: "false"
    # service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
    # service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    # service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /health/live
    # service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: http


fluentbit:
  image:
    repository: fluent/fluent-bit
    tag: 1.8
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

fluenthose:
  args:
    - "serve"
    - "--log-level" 
    - "info"
  image:
    repository: quay.io/betsson-oss/fluenthose
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
